# Uncomment this line to define a global platform for your project
platform :ios, ‘9.3’
# Uncomment this line if you're using Swift
 use_frameworks!

target 'EcoLight' do
       pod 'RealmSwift'
       pod 'SVProgressHUD'
       pod 'Alamofire', '~> 3.0'
end

